version: '3.3'

services:
  hub-communication-api:
    restart: always
    container_name: hub-communication-api
    build: .
    ports: 
      - 9229:9229
      - 3000:3000
    expose:
      - 9229
      - 3000
    volumes:
      - .:/app
    networks:
      - hub-communication
    command: yarn start:debug
    depends_on:
      - hub-communication-db
  hub-communication-db:
    container_name: hub-communication-db
    image: mongo
    restart: always
    ports:
      - 8081:8081
    volumes:
      - db_data:/data/db


networks:
  hub-communication: {}

volumes:
  db_data: {}
